packages:
  - .
  - docs
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@5.7.2"
engineStrict: true # engines.node will be strictly enforced when installing dependencies
allowBuilds:
  esbuild: true
  unrs-resolver: true
