packages:
  - .
  - docs
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@5.7.2"
  - "nanoid@3.3.14"
engineStrict: true # engines.node will be strictly enforced when installing dependencies
allowBuilds:
  esbuild: true
  unrs-resolver: true
shellEmulator: true
dedupePeers: true
packageExtensions:
  "@nolebase/vitepress-plugin-highlight-targeted-heading@*":
    peerDependencies:
      "@vueuse/core": "*"
