apiVersion: v1alpha1
kind: Setting
metadata:
  name: howiehz-higan-setting
spec:
  forms:
    - group: styles
      label: 总体样式
      formSchema:
        - $formkit: select
          name: color_schema
          label: 配色方案
          value: { theme: "auto", comment: "auto", color-scheme: "auto" }
          options:
            - label: 跟随系统
              value: { theme: "auto", comment: "auto", color-scheme: "auto" }
            - label: "暗色"
              value: { theme: "dark", comment: "dark", color-scheme: "dark" }
            - label: "亮色"
              value: { theme: "light", comment: "light", color-scheme: "light" }
            - label: "灰粉"
              value: { theme: "gray", comment: "light", color-scheme: "light" }
        - $formkit: select
          name: text_size
          label: 字体大小
          value: "small"
          options:
            - label: "小字体"
              value: "small"
            - label: "常规"
              value: "normal"
            - label: "大字体"
              value: "large"
        - $formkit: text
          name: max_width
          label: 内容区域最大宽度
          value: 48rem
          placeholder: "默认值: 48rem"
          help: "允许全部CSS长度单位, 如: 48rem, 780px, 70vw, 70%"
        - $formkit: attachment
          name: icon
          label: 首页头像
        - $formkit: radio
          name: avatar_circle
          label: 圆形头像
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: avatar_grayout
          label: 灰度头像
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: is_footer_theme_info_show
          label: 页面底部主题信息
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: is_footer_copyright_show
          label: 页面底部版权信息
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: is_footer_menu_show
          label: 页面底部菜单
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
    - group: index_styles
      label: 首页样式
      formSchema:
        - $formkit: select
          name: post_list_layout
          label: 文章列表布局
          value: "simple-post-list"
          options:
            - label: "简洁列表"
              value: "simple-post-list"
            - label: "多元列表"
              value: "post-list-summary"
        - $formkit: radio
          name: is_pin_icon_show
          label: 文章列表置顶图标
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: select
          name: pin_icon_position
          if: "$is_pin_icon_show===true"
          label: 置顶图标位置
          value: "right"
          options:
            - label: "标题左侧"
              value: "left"
            - label: "标题右侧"
              value: "right"
        - $formkit: radio
          name: hitokoto
          label: 一言 (hitokoto)
          value: false
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: radio
          name: is_resume_show
          label: 个人简介/公告栏
          value: false
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: code
          name: resume
          if: "$is_resume_show===true"
          label: 个人简介/公告栏内容（支持 html 代码块）
          language: html
          height: 150px
    - group: post_styles
      label: 文章页样式
      formSchema:
        - $formkit: radio
          name: post_title_uppper
          label: 文章标题大写
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
    - group: rss
      label: RSS
      formSchema:
        - $formkit: radio
          name: index_rss
          label: 首页RSS展示
          value: true
          attrs:
            icon: rss
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: text
          name: rss_url
          label: "RSS地址"
          value: "/rss.xml"
    - group: sns
      label: 社交资料
      formSchema:
        - $formkit: code
          name: guide
          label: 填写指南
          value: " X, Facebook, Instagram, Dribbble, Github 仅需填入用户名；\n
          微博, Telegram, Reddit 仅需填入 ID；\n
          bilibili 仅需填入 uid；\n
          QQ 仅需填入 QQ 号；\n
          邮箱仅需填入邮箱地址；\n
          Stack Overflow 仅需填写个人主页网址在 users/ 后的部分；\n
          知乎仅需填写个人主页网址在 people/ 后的部分；\n
          YouTube 仅需填写频道网址在 channel/ 后的部分；\n
          网易云音乐仅需填写个人主页网址在 ?id= 后的部分；\n
          豆瓣仅需填写个人主页网址在 people/ 后的部分；\n"
          language: html
          height: 210px
        - $formkit: repeater
          name: index_sns
          label: 首页社交资料展示
          value: []
          children:
            - $formkit: select
              name: type
              label: 类型
              validation: "required"
              placeholder: "请选择你要展示的社交资料"
              options:
                - label: BiliBili
                  value:
                    {
                      url: "https://space.bilibili.com/",
                      aria-label: "Find me on BiliBili",
                      data-icon: simple-icons:bilibili,
                    }
                - label: Dribbble
                  value:
                    {
                      url: "https://dribbble.com/",
                      aria-label: "Find me on Dribbble",
                      data-icon: ant-design:dribbble-circle-filled,
                    }
                - label: Email
                  value: { url: "mailto:", aria-label: "Find me on Email", data-icon: ph:envelope-simple-bold }
                - label: Facebook
                  value:
                    {
                      url: "https://www.facebook.com/",
                      aria-label: "Find me on facebook",
                      data-icon: ic:baseline-facebook,
                    }
                - label: Github
                  value: { url: "https://github.com/", aria-label: "Find me on Github", data-icon: mdi:github }
                - label: Instagram
                  value:
                    {
                      url: "https://www.instagram.com/",
                      aria-label: "Find me on Instagram",
                      data-icon: ant-design:instagram-filled,
                    }
                - label: QQ
                  value:
                    {
                      url: "tencent://message/?Site=&Menu=yes&uin=",
                      aria-label: "Find me on QQ",
                      data-icon: ant-design:qq-circle-filled,
                    }
                - label: Reddit
                  value:
                    {
                      url: "https://www.reddit.com/user/",
                      aria-label: "Find me on Reddit",
                      data-icon: ant-design:reddit-circle-filled,
                    }
                - label: "Stack Overflow"
                  value:
                    {
                      url: "https://stackoverflow.com/users/",
                      aria-label: "Find me on Stack Overflow",
                      data-icon: mdi:stack-overflow,
                    }
                - label: Telegram
                  value: { url: "https://t.me/", aria-label: "Find me on Telegram", data-icon: ic:baseline-telegram }
                - label: X
                  value:
                    { url: "https://x.com/", aria-label: "Find me on X", data-icon: ant-design:twitter-circle-filled }
                - label: YouTube
                  value:
                    {
                      url: "https://www.youtube.com/channel/",
                      aria-label: "Find me on YouTube",
                      data-icon: ant-design:youtube-filled,
                    }
                - label: 豆瓣
                  value:
                    {
                      url: "https://www.douban.com/people/",
                      aria-label: "Find me on douban",
                      data-icon: ri:douban-line,
                    }
                - label: 网易云音乐
                  value:
                    {
                      url: "https://music.163.com/#/user/home?id=",
                      aria-label: "Find me on NetEase CloudMusic",
                      data-icon: simple-icons:neteasecloudmusic,
                    }
                - label: 微博
                  value:
                    {
                      url: "https://weibo.com/",
                      aria-label: "Find me on weibo",
                      data-icon: ant-design:weibo-circle-filled,
                    }
                - label: 知乎
                  value:
                    {
                      url: "https://www.zhihu.com/people/",
                      aria-label: "Find me on zhihu",
                      data-icon: ant-design:zhihu-circle-filled,
                    }
            - $formkit: text
              name: input_value
              label: 值
              validation: "required"
