apiVersion: v1alpha1
kind: Setting
metadata:
  name: howiehz-higan-setting
spec:
  forms:
    - group: styles
      label: 总体样式
      formSchema:
        - $formkit: select
          name: color_schema
          label: 配色方案
          value: { theme: "auto", comment: "auto", color-scheme: "auto" }
          options:
            - label: 跟随系统
              value: { theme: "auto", comment: "auto", color-scheme: "auto" }
            - label: "暗色"
              value: { theme: "dark", comment: "dark", color-scheme: "dark" }
            - label: "亮色"
              value: { theme: "light", comment: "light", color-scheme: "light" }
            - label: "灰粉"
              value: { theme: "gray", comment: "light", color-scheme: "light" }
        - $formkit: select
          name: text_size
          label: 字体大小
          value: "small"
          options:
            - label: "小字体"
              value: "small"
            - label: "常规"
              value: "normal"
            - label: "大字体"
              value: "large"
        - $formkit: text
          name: max_width
          label: 内容区域最大宽度
          value: 48rem
          placeholder: "默认值: 48rem"
          help: "允许全部CSS长度单位, 如: 48rem, 780px, 70vw, 70%"
        - $formkit: attachment
          name: icon
          label: 首页头像
        - $formkit: radio
          name: avatar_circle
          label: 圆形头像
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: avatar_grayout
          label: 开启灰度头像
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
    - group: index_styles
      label: 首页样式
      formSchema:
        - $formkit: select
          name: post_list_layout
          label: 文章列表布局
          value: "simple-post-list"
          options:
            - label: "简洁列表"
              value: "simple-post-list"
            - label: "多元列表"
              value: "post-list-summary"
        - $formkit: radio
          name: hitokoto
          label: 开启一言 (hitokoto)
          value: false
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: radio
          name: is_resume_show
          label: 开启个人简介
          value: false
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: code
          name: resume
          if: "$is_resume_show===true"
          label: 个人简介
          language: html
          height: 150px
    - group: post_styles
      label: 文章页样式
      formSchema:
        - $formkit: radio
          name: post_title_uppper
          label: 文章标题大写
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
    - group: rss
      label: RSS
      formSchema:
        - $formkit: radio
          name: index_rss
          label: 首页RSS展示
          value: true
          attrs:
            icon: rss
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: text
          name: rss_url
          label: "RSS地址"
          value: "/rss.xml"
    - group: sns
      label: 社交资料
      formSchema:
        - $formkit: repeater
          name: index_sns
          label: 首页社交资料展示
          value: []
          children:
            - $formkit: select
              name: type
              label: 类型
              placeholder: "选择你要展示的社交资料"
              options:
                - label: X
                  help: "只需填入 X 用户名即可"
                  value: { url: "https://x.com/", aria-label: "Find me on X", data-icon: mdi:twitter }
                - label: Facebook
                  help: "只需填入 Facebook 用户名即可"
                  value:
                    {
                      url: "https://www.facebook.com/",
                      aria-label: "Find me on facebook",
                      data-icon: ic:baseline-facebook,
                    }
                - label: Instagram
                  help: "只需填入 Instagram 用户名即可"
                  value:
                    { url: "https://www.instagram.com/", aria-label: "Find me on instagram", data-icon: mdi:instagram }
                - label: Dribbble
                  help: "只需填入 Dribbble 用户名即可"
                  value: { url: "https://dribbble.com/", aria-label: "Find me on dribbble", data-icon: mdi:dribbble }
                - label: 微博
                  help: "只需填入微博 Id 即可"
                  value: { url: "https://weibo.com/", aria-label: "Find me on weibo", data-icon: bi:sina-weibo }
                - label: Email
                  help: "只需填入邮箱地址即可"
                  value: { url: "mailto:", aria-label: "Find me on email", data-icon: ph:envelope-simple-bold }
                - label: Github
                  help: "只需填入 Github 用户名即可"
                  value: { url: "https://github.com/", aria-label: "Find me on github", data-icon: mdi:github }
                - label: QQ
                  help: "只需填入 QQ 号即可"
                  value:
                    {
                      url: "tencent://message/?Site=&Menu=yes&uin=",
                      aria-label: "Find me on QQ",
                      data-icon: ant-design:qq-circle-filled,
                    }
                - label: Telegram
                  help: "只需填入 Telegram Id 即可"
                  value: { url: "https://t.me/", aria-label: "Find me on telegram", data-icon: ic:baseline-telegram }
            - $formkit: text
              name: input_value
              label: 值
              validation: "required"
