apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: howiehz-higan
spec:
  displayName: 彼岸-皓改
  author:
    name: HowieHz
    website: https://howiehz.top
  description: 生死为此岸，涅槃为彼岸；有苦无乐为此岸，无苦无乐为彼岸...它代表着对一切美好的精神追求，也代表着生生不息的轮回亦如本主题分黑白两色，阴极阳至，向死而生。
  logo: /themes/guqing-higan/assets/images/logo.png
  website: https://howiehz.top
  repo: https://github.com/howiehz/halo-theme-higan-hz
  settingName: howiehz-higan-setting
  configMapName: howiehz-higan-configmap
  version: 1.0.1
  requires: ">=2.1.0"
