apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: howiehz-higan
  annotations:
    store.halo.run/app-id: app-homxf
spec:
  displayName: Higan Haozi
  author:
    name: HowieHz
    website: https://howiehz.top
  description: 生死为此岸，涅槃为彼岸；有苦无乐为此岸，无苦无乐为彼岸...它代表着对一切美好的精神追求，也代表着生生不息的轮回亦如本主题分黑白两色，阴极阳至，向死而生。
  logo: /themes/howiehz-higan/assets/images/logo.png
  homepage: https://howiehz.top/halo-theme-higan-haozi
  repo: https://github.com/howiehz/halo-theme-higan-hz.git
  issues: https://github.com/howiehz/halo-theme-higan-hz/issues
  settingName: howiehz-higan-setting
  configMapName: howiehz-higan-configmap
  version: 1.52.1
  requires: ">=2.22.1"
  license:
    - name: "MIT"
      url: "https://github.com/howiehz/halo-theme-higan-hz/blob/main/LICENSE"
  customTemplates:
    page:
      - name: 文章页样式
        description: 自定义页面将使用类似文章页的布局和样式，主要体现在桌面端顶部菜单（侧边目录，回到顶端按钮，分享菜单），移动端底部菜单（类似文章页）。菜单、目录相关设置与“文章页样式”下的设置保持一致。
        screenshot:
        file: page-like-post-style.html
