import { mkdirSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";

import manifest from "../../../templates/.vite/manifest.json" with { type: "json" };

function resolveManifestCss(
  manifestData: Record<
    string,
    {
      file: string;
      src?: string;
      css?: string[];
      imports?: string[];
    }
  >,
  entryKeys: string[],
): string[] {
  const cssFiles = new Set<string>();
  const visited = new Set<string>();

  function visit(entryKey: string): void {
    if (visited.has(entryKey)) return;
    visited.add(entryKey);

    const chunk = manifestData[entryKey];
    if (!chunk) {
      throw new Error(`Manifest entry not found: ${entryKey}`);
    }

    for (const importedEntryKey of chunk.imports ?? []) {
      visit(importedEntryKey);
    }

    if (chunk.file.endsWith(".css")) {
      cssFiles.add(chunk.file);
    }

    for (const cssFile of chunk.css ?? []) {
      cssFiles.add(cssFile);
    }
  }

  for (const entryKey of entryKeys) {
    visit(entryKey);
  }

  return [...cssFiles];
}

const templatesDir = resolve(import.meta.dirname, "../../../templates");
const generatedDir = resolve(import.meta.dirname, "../generated");

const previewCssEntries = [
  {
    outputFile: "error.css",
    entryKeys: [
      "components/theme-dark/template.html",
      "components/theme-light/template.html",
      "components/text-size-normal/template.html",
      "components/base-layout/template.html",
      "_runtime/pages/error/index.ts",
    ],
  },
  {
    outputFile: "post.css",
    entryKeys: [
      "components/theme-dark/template.html",
      "components/theme-light/template.html",
      "components/text-size-normal/template.html",
      "components/base-layout/template.html",
      "post.html",
    ],
  },
] as const;

mkdirSync(generatedDir, { recursive: true });

for (const { outputFile, entryKeys } of previewCssEntries) {
  const content = [
    "/* This file is auto-generated by docs/.vitepress/scripts/generate-preview-css.ts. */",
    ...resolveManifestCss(manifest, [...entryKeys]).map(
      (cssFile) => `@import "${relative(generatedDir, resolve(templatesDir, cssFile)).replaceAll("\\", "/")}";`,
    ),
    "",
  ].join("\n");

  writeFileSync(resolve(generatedDir, outputFile), content, "utf8");
}
