<script setup>
import { onMounted, ref } from "vue";
// Special api to mount the app
import { createApp } from "whyframe:app";

import { extendStylesScope, initHeadingAnchors, trackColorScheme } from "./frame-preview-dom";

const el = ref();

onMounted(async () => {
  trackColorScheme();
  // Mount the app to the ref
  createApp(el.value).then(() => {
    initHeadingAnchors("article > .content");
    // initHeadingAnchors 需在 extendStylesScope 之前调用，确保 JS 动态插入的元素（如 .heading-anchor）
    // 也能被 extendStylesScope 的 BFS 遍历覆盖，从而获得 scoped CSS 所需的 data-v-* 属性。
    extendStylesScope(el.value);
  });
});
</script>

<template>
  <article
    id="article-tag"
    class="post"
  >
    <div
      id="vp-app"
      ref="el"
      class="content loading"
    />
  </article>
</template>

<style src="./default.css" scoped></style>
<!-- This file is auto-generated by docs/.vitepress/scripts/generate-preview-css.ts. -->
<style src="../generated/post.css" scoped></style>
