<script setup>
import { onMounted, ref } from "vue";
// Special api to mount the app
import { createApp } from "whyframe:app";

import { extendStylesScope, trackColorScheme } from "./frame-runtime";

const el = ref();

onMounted(async () => {
  trackColorScheme();
  // Mount the app to the ref
  createApp(el.value).then(() => {
    extendStylesScope(el.value);
  });
});
</script>

<template>
  <div
    id="vp-app"
    ref="el"
    class="content loading"
  />
</template>

<style src="./default.css" scoped></style>
<!-- This file is auto-generated by docs/.vitepress/scripts/generate-preview-css.ts. -->
<style src="../generated/error.css" scoped></style>
