name: Build Theme
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Upload Theme
    permissions:
      contents: read
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: ./.github/workflows/reusable-build-theme.yml
    with:
      theme_ref: ${{ github.sha }}
      artifact_name: theme-artifact
