name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Upload Theme
    runs-on: ubuntu-latest
    steps:
      - name: Make Build Directory
        run: |
          pwd
          mkdir -p ~/builds/tmp ~/builds/target
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: true
      - name: Build project
        run: pnpm build
      - name: Copy Theme Files from Original to Temp
        run: |
          pwd
          cp -r . ~/builds/tmp
      - name: Remove excluded files
        run: |
          pwd
          cd ~/builds/tmp
          pwd
          cat ~/work/halo-theme-higan-hz/halo-theme-higan-hz/.github/exclude-list.txt | xargs rm -rvf
      - name: Zip Theme in Chinese
        run: |
          pwd
          cd ~/builds/tmp
          pwd

          zip -9 -r howiehz-higan-cn.zip .

          rm settings.yaml annotation-settings.yaml theme.yaml
          mv ~/work/halo-theme-higan-hz/halo-theme-higan-hz/settings.yaml settings.yaml
          mv ~/work/halo-theme-higan-hz/halo-theme-higan-hz/annotation-settings.yaml annotation-settings.yaml
          mv ~/work/halo-theme-higan-hz/halo-theme-higan-hz/theme.yaml theme.yaml
          zip -9 -r howiehz-higan-cn.zip settings.yaml annotation-settings.yaml theme.yaml

          mv howiehz-higan-cn.zip ~/builds/target
      - name: Zip Theme in English
        run: |
          pwd
          cd ~/builds/tmp
          pwd

          zip -9 -r howiehz-higan-en.zip .

          rm settings.yaml annotation-settings.yaml theme.yaml
          mv ~/work/halo-theme-higan-hz/halo-theme-higan-hz/i18n-settings/settings.en.yaml settings.yaml
          mv ~/work/halo-theme-higan-hz/halo-theme-higan-hz/i18n-settings/annotation-settings.en.yaml annotation-settings.yaml
          mv ~/work/halo-theme-higan-hz/halo-theme-higan-hz/i18n-settings/theme.en.yaml theme.yaml
          zip -9 -r howiehz-higan-en.zip settings.yaml annotation-settings.yaml theme.yaml

          mv howiehz-higan-en.zip ~/builds/target
      - name: Upload Theme Build Target
        uses: actions/upload-artifact@v4
        with:
          name: theme-artifact
          path: ~/builds/target/*
