name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Upload Theme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Zip
        run: |
          mkdir -p ~/builds/target
          zip -r howiehz-higan-cn.zip . -x .eslintrc.cjs .hintrc .prettierignore index.html package.json pnpm-lock.yaml postcss.config.js prettier.config.js .husky/\* src/\* i18n-settings/\* screenshots/\* .git/\* .github/\* node_modules/\* .gitignore .editorconfig .eslintignore .eslintrc.js .prettierrc.js .stylelintrc.js .vscode/\* .nuxt/\* .nuxtignore .env .env.development .env.production .env.test .env.local .env.development.local .env.production.local .env.test.local
          mv howiehz-higan-cn.zip ~/builds/target
          zip -r howiehz-higan-en.zip . -x .eslintrc.cjs .hintrc .prettierignore index.html package.json pnpm-lock.yaml postcss.config.js prettier.config.js .husky/\* src/\* i18n-settings/\* screenshots/\* .git/\* .github/\* node_modules/\* .gitignore .editorconfig .eslintignore .eslintrc.js .prettierrc.js .stylelintrc.js .vscode/\* .nuxt/\* .nuxtignore .env .env.development .env.production .env.test .env.local .env.development.local .env.production.local .env.test.local settings.yaml
          mv howiehz-higan-en.zip ~/builds/target
          rm settings.yaml
          mv i18n-settings/settings.en.yaml settings.yaml
          zip -r ~/builds/target/howiehz-higan-en.zip settings.yaml
      - name: Upload Theme Build Target
        uses: actions/upload-artifact@v4
        with:
          name: theme-artifact
          path: ~/builds/target/*
