name: Update Visual Regression Screenshots

on:
  workflow_dispatch:

jobs:
  update-screenshots:
    if: github.ref_name != github.event.repository.default_branch
    concurrency:
      group: visual-regression-screenshots@${{ github.ref_name }}
      cancel-in-progress: true
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-vitest-visual.yml
    with:
      theme_ref: ${{ github.sha }}
      ref_name: update
      playwright_browsers: chromium
      upload_artifact: true
      update_screenshots: true
